<?php

if (!defined('APP_NOTICE_DOMAIN')) {
    define('APP_NOTICE_DOMAIN', config('shop.app_notice_domain'));
}
if (!defined('DEFAULT_LANGUAGE')) {
    define('DEFAULT_LANGUAGE', config('shop.default_language'));
}
if (!defined('TRANSLATION_ENABLED')) {
    define('TRANSLATION_ENABLED', config('shop.translation_enabled'));
}
if (!defined('DEFAULT_CURRENCY')) {
    define('DEFAULT_CURRENCY', config('shop.default_currency'));
}
if (!defined('DEFAULT_CURRENCY_FORMATION')) {
    define('DEFAULT_CURRENCY_FORMATION', 'en-US');
}
if (!defined('ACTIVE_PAYMENT_GATEWAY')) {
    define('ACTIVE_PAYMENT_GATEWAY', config('shop.active_payment_gateway'));
}
if (!defined('NOT_FOUND')) {
    define('NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.NOT_FOUND');
}
if (!defined('COUPON_NOT_FOUND')) {
    define('COUPON_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.COUPON_NOT_FOUND');
}
if (!defined('INVALID_COUPON_CODE')) {
    define('INVALID_COUPON_CODE', APP_NOTICE_DOMAIN . 'ERROR.INVALID_COUPON_CODE');
}
if (!defined('COUPON_CODE_IS_NOT_APPLICABLE')) {
    define('COUPON_CODE_IS_NOT_APPLICABLE', APP_NOTICE_DOMAIN . 'ERROR.COUPON_CODE_IS_NOT_APPLICABLE');
}
if (!defined('ALREADY_FREE_SHIPPING_ACTIVATED')) {
    define('ALREADY_FREE_SHIPPING_ACTIVATED', APP_NOTICE_DOMAIN . 'ERROR.ALREADY_FREE_SHIPPING_ACTIVATED');
}
if (!defined('CART_ITEMS_NOT_FOUND')) {
    define('CART_ITEMS_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.CART_ITEMS_NOT_FOUND');
}
if (!defined('NOT_A_RENTAL_PRODUCT')) {
    define('NOT_A_RENTAL_PRODUCT', APP_NOTICE_DOMAIN . 'ERROR.NOT_A_RENTAL_PRODUCT');
}
if (!defined('NOT_AUTHORIZED')) {
    define('NOT_AUTHORIZED', APP_NOTICE_DOMAIN . 'ERROR.NOT_AUTHORIZED');
}
if (!defined('SOMETHING_WENT_WRONG')) {
    define('SOMETHING_WENT_WRONG', APP_NOTICE_DOMAIN . 'ERROR.SOMETHING_WENT_WRONG');
}
if (!defined('PAYMENT_FAILED')) {
    define('PAYMENT_FAILED', APP_NOTICE_DOMAIN . 'ERROR.PAYMENT_FAILED');
}
if (!defined('SHOP_NOT_APPROVED')) {
    define('SHOP_NOT_APPROVED', APP_NOTICE_DOMAIN . 'ERROR.SHOP_NOT_APPROVED');
}
if (!defined('INSUFFICIENT_BALANCE')) {
    define('INSUFFICIENT_BALANCE', APP_NOTICE_DOMAIN . 'ERROR.INSUFFICIENT_BALANCE');
}
if (!defined('INVALID_CREDENTIALS')) {
    define('INVALID_CREDENTIALS', APP_NOTICE_DOMAIN . 'ERROR.INVALID_CREDENTIALS');
}
if (!defined('EMAIL_SENT_SUCCESSFUL')) {
    define('EMAIL_SENT_SUCCESSFUL', APP_NOTICE_DOMAIN . 'MESSAGE.EMAIL_SENT_SUCCESSFUL');
}
if (!defined('PASSWORD_RESET_SUCCESSFUL')) {
    define('PASSWORD_RESET_SUCCESSFUL', APP_NOTICE_DOMAIN . 'MESSAGE.PASSWORD_RESET_SUCCESSFUL');
}
if (!defined('INVALID_TOKEN')) {
    define('INVALID_TOKEN', APP_NOTICE_DOMAIN . 'MESSAGE.INVALID_TOKEN');
}
if (!defined('TOKEN_IS_VALID')) {
    define('TOKEN_IS_VALID', APP_NOTICE_DOMAIN . 'MESSAGE.TOKEN_IS_VALID');
}
if (!defined('CHECK_INBOX_FOR_PASSWORD_RESET_EMAIL')) {
    define('CHECK_INBOX_FOR_PASSWORD_RESET_EMAIL', APP_NOTICE_DOMAIN . 'MESSAGE.CHECK_INBOX_FOR_PASSWORD_RESET_EMAIL');
}
if (!defined('ACTION_NOT_VALID')) {
    define('ACTION_NOT_VALID', APP_NOTICE_DOMAIN . 'ERROR.ACTION_NOT_VALID');
}
if (!defined('PLEASE_LOGIN_USING_FACEBOOK_OR_GOOGLE')) {
    define('PLEASE_LOGIN_USING_FACEBOOK_OR_GOOGLE', APP_NOTICE_DOMAIN . 'ERROR.PLEASE_LOGIN_USING_FACEBOOK_OR_GOOGLE');
}
if (!defined('WITHDRAW_MUST_BE_ATTACHED_TO_SHOP')) {
    define('WITHDRAW_MUST_BE_ATTACHED_TO_SHOP', APP_NOTICE_DOMAIN . 'ERROR.WITHDRAW_MUST_BE_ATTACHED_TO_SHOP');
}
if (!defined('OLD_PASSWORD_INCORRECT')) {
    define('OLD_PASSWORD_INCORRECT', APP_NOTICE_DOMAIN . 'MESSAGE.OLD_PASSWORD_INCORRECT');
}
if (!defined('OTP_SEND_FAIL')) {
    define('OTP_SEND_FAIL', APP_NOTICE_DOMAIN . 'ERROR.OTP_SEND_FAIL');
}
if (!defined('OTP_SEND_SUCCESSFUL')) {
    define('OTP_SEND_SUCCESSFUL', APP_NOTICE_DOMAIN . 'MESSAGE.OTP_SEND_SUCCESSFUL');
}
if (!defined('REQUIRED_INFO_MISSING')) {
    define('REQUIRED_INFO_MISSING', APP_NOTICE_DOMAIN . 'MESSAGE.REQUIRED_INFO_MISSING');
}
if (!defined('CONTACT_UPDATE_SUCCESSFUL')) {
    define('CONTACT_UPDATE_SUCCESSFUL', APP_NOTICE_DOMAIN . 'MESSAGE.CONTACT_UPDATE_SUCCESSFUL');
}
if (!defined('INVALID_GATEWAY')) {
    define('INVALID_GATEWAY', APP_NOTICE_DOMAIN . 'ERROR.INVALID_GATEWAY');
}
if (!defined('OTP_VERIFICATION_FAILED')) {
    define('OTP_VERIFICATION_FAILED', APP_NOTICE_DOMAIN . 'ERROR.OTP_VERIFICATION_FAILED');
}
if (!defined('CONTACT_UPDATE_FAILED')) {
    define('CONTACT_UPDATE_FAILED', APP_NOTICE_DOMAIN . 'ERROR.CONTACT_UPDATE_FAILED');
}
if (!defined('ALREADY_REFUNDED')) {
    define('ALREADY_REFUNDED', APP_NOTICE_DOMAIN . 'ERROR.ALREADY_REFUNDED');
}
if (!defined('ORDER_ALREADY_HAS_REFUND_REQUEST')) {
    define('ORDER_ALREADY_HAS_REFUND_REQUEST', APP_NOTICE_DOMAIN . 'ERROR.ORDER_ALREADY_HAS_REFUND_REQUEST');
}
if (!defined('REFUND_ONLY_ALLOWED_FOR_MAIN_ORDER')) {
    define('REFUND_ONLY_ALLOWED_FOR_MAIN_ORDER', APP_NOTICE_DOMAIN . 'ERROR.REFUND_ONLY_ALLOWED_FOR_MAIN_ORDER');
}
if (!defined('WRONG_REFUND')) {
    define('WRONG_REFUND', APP_NOTICE_DOMAIN . 'ERROR.WRONG_REFUND');
}
if (!defined('CSV_NOT_FOUND')) {
    define('CSV_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.CSV_NOT_FOUND');
}
if (!defined('ALREADY_GIVEN_REVIEW_FOR_THIS_PRODUCT')) {
    define('ALREADY_GIVEN_REVIEW_FOR_THIS_PRODUCT', APP_NOTICE_DOMAIN . 'ERROR.ALREADY_GIVEN_REVIEW_FOR_THIS_PRODUCT');
}
if (!defined('USER_NOT_FOUND')) {
    define('USER_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.USER_NOT_FOUND');
}
if (!defined('TOKEN_NOT_FOUND')) {
    define('TOKEN_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.TOKEN_NOT_FOUND');
}
if (!defined('NOT_AVAILABLE_FOR_BOOKING')) {
    define('NOT_AVAILABLE_FOR_BOOKING', APP_NOTICE_DOMAIN . 'ERROR.NOT_AVAILABLE_FOR_BOOKING');
}
if (!defined('YOU_HAVE_ALREADY_GIVEN_ABUSIVE_REPORT_FOR_THIS')) {
    define('YOU_HAVE_ALREADY_GIVEN_ABUSIVE_REPORT_FOR_THIS', APP_NOTICE_DOMAIN . 'ERROR.YOU_HAVE_ALREADY_GIVEN_ABUSIVE_REPORT_FOR_THIS');
}
if (!defined('MAXIMUM_QUESTION_LIMIT_EXCEEDED')) {
    define('MAXIMUM_QUESTION_LIMIT_EXCEEDED', APP_NOTICE_DOMAIN . 'ERROR.MAXIMUM_QUESTION_LIMIT_EXCEEDED');
}
if (!defined('INVALID_AMOUNT')) {
    define('INVALID_AMOUNT', APP_NOTICE_DOMAIN . 'ERROR.INVALID_AMOUNT');
}
if (!defined('INVALID_CARD')) {
    define('INVALID_CARD', APP_NOTICE_DOMAIN . 'ERROR.INVALID_CARD');
}
if (!defined('TOO_MANY_REQUEST')) {
    define('TOO_MANY_REQUEST', APP_NOTICE_DOMAIN . 'ERROR.TOO_MANY_REQUEST');
}
if (!defined('INVALID_REQUEST')) {
    define('INVALID_REQUEST', APP_NOTICE_DOMAIN . 'ERROR.INVALID_REQUEST');
}
if (!defined('AUTHENTICATION_FAILED')) {
    define('AUTHENTICATION_FAILED', APP_NOTICE_DOMAIN . 'ERROR.AUTHENTICATION_FAILED');
}
if (!defined('API_CONNECTION_FAILED')) {
    define('API_CONNECTION_FAILED', APP_NOTICE_DOMAIN . 'ERROR.API_CONNECTION_FAILED');
}
if (!defined('SOMETHING_WENT_WRONG_WITH_PAYMENT')) {
    define('SOMETHING_WENT_WRONG_WITH_PAYMENT', APP_NOTICE_DOMAIN . 'ERROR.SOMETHING_WENT_WRONG_WITH_PAYMENT');
}
if (!defined('INVALID_PAYMENT_ID')) {
    define('INVALID_PAYMENT_ID', APP_NOTICE_DOMAIN . 'ERROR.INVALID_PAYMENT_ID');
}
if (!defined('INVALID_PAYMENT_INTENT_ID')) {
    define('INVALID_PAYMENT_INTENT_ID', APP_NOTICE_DOMAIN . 'ERROR.INVALID_PAYMENT_INTENT_ID');
}
if (!defined('EMAIL_NOT_VERIFIED')) {
    define('EMAIL_NOT_VERIFIED', 'EMAIL_NOT_VERIFIED');
}
if (!defined('INVALID_LICENSE_KEY')) {
    define('INVALID_LICENSE_KEY', 'INVALID_LICENSE_KEY');
}
if (!defined('EMAIL_UPDATED_SUCCESSFULLY')) {
    define('EMAIL_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'SUCCESS.EMAIL_UPDATED_SUCCESSFULLY');
}
if (!defined('YOU_CAN_NOT_SEND_MESSAGE_TO_YOUR_OWN_SHOP')) {
    define('YOU_CAN_NOT_SEND_MESSAGE_TO_YOUR_OWN_SHOP', APP_NOTICE_DOMAIN . 'ERROR.YOU_CAN_NOT_SEND_MESSAGE_TO_YOUR_OWN_SHOP');
}
if (!defined('COULD_NOT_CREATE_THE_RESOURCE')) {
    define('COULD_NOT_CREATE_THE_RESOURCE', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_CREATE_THE_RESOURCE');
}
if (!defined('COULD_NOT_UPDATE_THE_RESOURCE')) {
    define('COULD_NOT_UPDATE_THE_RESOURCE', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_UPDATE_THE_RESOURCE');
}
if (!defined('COULD_NOT_DELETE_THE_RESOURCE')) {
    define('COULD_NOT_DELETE_THE_RESOURCE', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_DELETE_THE_RESOURCE');
}
if (!defined('PLEASE_ENABLE_OPENAI_FROM_THE_SETTINGS')) {
    define('PLEASE_ENABLE_OPENAI_FROM_THE_SETTINGS', APP_NOTICE_DOMAIN . 'ERROR.PLEASE_ENABLE_OPENAI_FROM_THE_SETTINGS');
}
if (!defined('DUMMY_DATA_PATH')) {
    define('DUMMY_DATA_PATH', config('shop.dummy_data_path'));
}
if (!defined('THIS_COUPON_CODE_IS_ONLY_FOR_VERIFIED_USERS')) {
    define('THIS_COUPON_CODE_IS_ONLY_FOR_VERIFIED_USERS', APP_NOTICE_DOMAIN . 'ERROR.THIS_COUPON_CODE_IS_ONLY_FOR_VERIFIED_USERS');
}
if (!defined('THIS_COUPON_CODE_IS_NOT_APPROVED')) {
    define('THIS_COUPON_CODE_IS_NOT_APPROVED', APP_NOTICE_DOMAIN . 'ERROR.THIS_COUPON_CODE_IS_NOT_APPROVED');
}
if (!defined('COUPON_CODE_IS_NOT_APPLICABLE_IN_THIS_SHOP_PRODUCT')) {
    define('COUPON_CODE_IS_NOT_APPLICABLE_IN_THIS_SHOP_PRODUCT', APP_NOTICE_DOMAIN . 'ERROR.COUPON_CODE_IS_NOT_APPLICABLE_IN_THIS_SHOP_PRODUCT');
}
if (!defined('PLEASE_ENABLE_PAYMENT_OPTION_FROM_THE_SETTINGS')) {
    define('PLEASE_ENABLE_PAYMENT_OPTION_FROM_THE_SETTINGS', APP_NOTICE_DOMAIN . 'ERROR.PLEASE_ENABLE_PAYMENT_OPTION_FROM_THE_SETTINGS');
}
if (!defined('COULD_NOT_SETTLE_THE_TRANSITION')) {
    define('COULD_NOT_SETTLE_THE_TRANSITION', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_SETTLE_THE_TRANSITION');
}
if (!defined('USER_ACTIVATED_SUCCESSFULLY')) {
    define('USER_ACTIVATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_ACTIVATED_SUCCESSFULLY');
}
if (!defined('USER_DEACTIVATED_SUCCESSFULLY')) {
    define('USER_DEACTIVATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_DEACTIVATED_SUCCESSFULLY');
}
if (!defined('USER_LOGGED_OUT_SUCCESSFULLY')) {
    define('USER_LOGGED_OUT_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_LOGGED_OUT_SUCCESSFULLY');
}
if (!defined('ADDRESS_FOUND')) {
    define('ADDRESS_FOUND', APP_NOTICE_DOMAIN . 'MESSAGE.ADDRESS_FOUND');
}
if (!defined('ADDRESS_NOT_FOUND')) {
    define('ADDRESS_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.ADDRESS_NOT_FOUND');
}
if (!defined('ADDRESS_UPDATED')) {
    define('ADDRESS_UPDATED', APP_NOTICE_DOMAIN . 'MESSAGE.ADDRESS_UPDATED');
}
if (!defined('ADDRESS_DELETED')) {
    define('ADDRESS_DELETED', APP_NOTICE_DOMAIN . 'MESSAGE.ADDRESS_DELETED');
}
if (!defined('CATEGORY_CREATED_SUCCESSFULLY')) {
    define('CATEGORY_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CATEGORY_CREATED_SUCCESSFULLY');
}
if (!defined('CATEGORY_UPDATED_SUCCESSFULLY')) {
    define('CATEGORY_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CATEGORY_UPDATED_SUCCESSFULLY');
}
if (!defined('CATEGORY_DELETED_SUCCESSFULLY')) {
    define('CATEGORY_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CATEGORY_DELETED_SUCCESSFULLY');
}
if (!defined('CATEGORY_FEATURE_TOGGLED_SUCCESSFULLY')) {
    define('CATEGORY_FEATURE_TOGGLED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CATEGORY_FEATURE_TOGGLED_SUCCESSFULLY');
}
if (!defined('FAQ_CREATED_SUCCESSFULLY')) {
    define('FAQ_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.FAQ_CREATED_SUCCESSFULLY');
}
if (!defined('FAQ_UPDATED_SUCCESSFULLY')) {
    define('FAQ_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.FAQ_UPDATED_SUCCESSFULLY');
}
if (!defined('FAQ_DELETED_SUCCESSFULLY')) {
    define('FAQ_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.FAQ_DELETED_SUCCESSFULLY');
}
if (!defined('FAQS_REORDERED_SUCCESSFULLY')) {
    define('FAQS_REORDERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.FAQS_REORDERED_SUCCESSFULLY');
}
if (!defined('ATTRIBUTE_CREATED_SUCCESSFULLY')) {
    define('ATTRIBUTE_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ATTRIBUTE_CREATED_SUCCESSFULLY');
}
if (!defined('ATTRIBUTE_UPDATED_SUCCESSFULLY')) {
    define('ATTRIBUTE_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ATTRIBUTE_UPDATED_SUCCESSFULLY');
}
if (!defined('ATTRIBUTE_DELETED_SUCCESSFULLY')) {
    define('ATTRIBUTE_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ATTRIBUTE_DELETED_SUCCESSFULLY');
}
if (!defined('ATTRIBUTE_VALUE_CREATED_SUCCESSFULLY')) {
    define('ATTRIBUTE_VALUE_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ATTRIBUTE_VALUE_CREATED_SUCCESSFULLY');
}
if (!defined('ATTRIBUTE_VALUE_UPDATED_SUCCESSFULLY')) {
    define('ATTRIBUTE_VALUE_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ATTRIBUTE_VALUE_UPDATED_SUCCESSFULLY');
}
if (!defined('ATTRIBUTE_VALUE_DELETED_SUCCESSFULLY')) {
    define('ATTRIBUTE_VALUE_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ATTRIBUTE_VALUE_DELETED_SUCCESSFULLY');
}
if (!defined('FETCH_DATA_SUCCESSFULLY')) {
    define('FETCH_DATA_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.FETCH_DATA_SUCCESSFULLY');
}
if (!defined('CREATE_FLASH_SALE_SUCCESSFULLY')) {
    define('CREATE_FLASH_SALE_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CREATE_FLASH_SALE_SUCCESSFULLY');
}
if (!defined('UPDATE_FLASH_SALE_SUCCESSFULLY')) {
    define('UPDATE_FLASH_SALE_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.UPDATE_FLASH_SALE_SUCCESSFULLY');
}
if (!defined('DELETE_FLASH_SALE_SUCCESSFULLY')) {
    define('DELETE_FLASH_SALE_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETE_FLASH_SALE_SUCCESSFULLY');
}
if (!defined('BANNER_CREATED_SUCCESSFULLY')) {
    define('BANNER_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BANNER_CREATED_SUCCESSFULLY');
}
if (!defined('BANNER_UPDATED_SUCCESSFULLY')) {
    define('BANNER_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BANNER_UPDATED_SUCCESSFULLY');
}
if (!defined('BANNER_DELETED_SUCCESSFULLY')) {
    define('BANNER_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BANNER_DELETED_SUCCESSFULLY');
}
if (!defined('SLIDER_CREATED_SUCCESSFULLY')) {
    define('SLIDER_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SLIDER_CREATED_SUCCESSFULLY');
}
if (!defined('SLIDER_UPDATED_SUCCESSFULLY')) {
    define('SLIDER_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SLIDER_UPDATED_SUCCESSFULLY');
}
if (!defined('SLIDER_DELETED_SUCCESSFULLY')) {
    define('SLIDER_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SLIDER_DELETED_SUCCESSFULLY');
}
if (!defined('CREATE_PRODUCT_SUCCESSFULLY')) {
    define('CREATE_PRODUCT_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CREATE_PRODUCT_SUCCESSFULLY');
}
if (!defined('UPDATE_PRODUCT_SUCCESSFULLY')) {
    define('UPDATE_PRODUCT_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.UPDATE_PRODUCT_SUCCESSFULLY');
}
if (!defined('DELETE_PRODUCT_SUCCESSFULLY')) {
    define('DELETE_PRODUCT_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETE_PRODUCT_SUCCESSFULLY');
}
if (!defined('PRODUCTS_DELETED_SUCCESSFULLY')) {
    define('PRODUCTS_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.PRODUCTS_DELETED_SUCCESSFULLY');
}
if (!defined('ADDED_TO_WISHLIST_SUCCESSFULLY')) {
    define('ADDED_TO_WISHLIST_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ADDED_TO_WISHLIST_SUCCESSFULLY');
}
if (!defined('ALREADY_ADDED_TO_WISHLIST_FOR_THIS_PRODUCT')) {
    define('ALREADY_ADDED_TO_WISHLIST_FOR_THIS_PRODUCT', APP_NOTICE_DOMAIN . 'ERROR.ALREADY_ADDED_TO_WISHLIST_FOR_THIS_PRODUCT');
}
if (!defined('REMOVED_FROM_WISHLIST_SUCCESSFULLY')) {
    define('REMOVED_FROM_WISHLIST_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.REMOVED_FROM_WISHLIST_SUCCESSFULLY');
}
if (!defined('INVALID_ITEM_DATA')) {
    define('INVALID_ITEM_DATA', APP_NOTICE_DOMAIN . 'ERROR.INVALID_ITEM_DATA');
}
if (!defined('CREATE_CART_SUCCESSFULLY')) {
    define('CREATE_CART_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CREATE_CART_SUCCESSFULLY');
}
if (!defined('UPDATE_CART_SUCCESSFULLY')) {
    define('UPDATE_CART_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.UPDATE_CART_SUCCESSFULLY');
}
if (!defined('DELETE_CART_SUCCESSFULLY')) {
    define('DELETE_CART_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETE_CART_SUCCESSFULLY');
}
if (!defined('DELETE_CART_ITEM_SUCCESSFULLY')) {
    define('DELETE_CART_ITEM_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETE_CART_ITEM_SUCCESSFULLY');
}
if (!defined('CREATED_COUPON_SUCCESSFULLY')) {
    define('CREATED_COUPON_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CREATED_COUPON_SUCCESSFULLY');
}
if (!defined('UPDATED_COUPON_SUCCESSFULLY')) {
    define('UPDATED_COUPON_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.UPDATED_COUPON_SUCCESSFULLY');
}
if (!defined('DELETED_COUPON_SUCCESSFULLY')) {
    define('DELETED_COUPON_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETED_COUPON_SUCCESSFULLY');
}
if (!defined('CREATED_PROMOTION_SUCCESSFULLY')) {
    define('CREATED_PROMOTION_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CREATED_PROMOTION_SUCCESSFULLY');
}
if (!defined('UPDATED_PROMOTION_SUCCESSFULLY')) {
    define('UPDATED_PROMOTION_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.UPDATED_PROMOTION_SUCCESSFULLY');
}
if (!defined('DELETED_PROMOTION_SUCCESSFULLY')) {
    define('DELETED_PROMOTION_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETED_PROMOTION_SUCCESSFULLY');
}
if (!defined('PERMISSION_MISSING_ROLES')) {
    define('PERMISSION_MISSING_ROLES', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_MISSING_ROLES');
}
if (!defined('PERMISSION_MISSING_PERMISSIONS')) {
    define('PERMISSION_MISSING_PERMISSIONS', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_MISSING_PERMISSIONS');
}
if (!defined('PERMISSION_MISSING_ROLES_OR_PERMISSIONS')) {
    define('PERMISSION_MISSING_ROLES_OR_PERMISSIONS', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_MISSING_ROLES_OR_PERMISSIONS');
}
if (!defined('PERMISSION_NECESSARY_ROLES')) {
    define('PERMISSION_NECESSARY_ROLES', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_NECESSARY_ROLES');
}
if (!defined('PERMISSION_NECESSARY_PERMISSIONS')) {
    define('PERMISSION_NECESSARY_PERMISSIONS', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_NECESSARY_PERMISSIONS');
}
if (!defined('PERMISSION_NECESSARY_ROLES_OR_PERMISSIONS')) {
    define('PERMISSION_NECESSARY_ROLES_OR_PERMISSIONS', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_NECESSARY_ROLES_OR_PERMISSIONS');
}
if (!defined('PERMISSION_MISSING_TRAIT_HAS_ROLES')) {
    define('PERMISSION_MISSING_TRAIT_HAS_ROLES', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_MISSING_TRAIT_HAS_ROLES');
}
if (!defined('USER_NOT_LOGGED_IN')) {
    define('USER_NOT_LOGGED_IN', APP_NOTICE_DOMAIN . 'ERROR.USER_NOT_LOGGED_IN');
}
if (!defined('PERMISSION_NOT_FOUND_BY_NAME')) {
    define('PERMISSION_NOT_FOUND_BY_NAME', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_NOT_FOUND_BY_NAME');
}
if (!defined('PERMISSION_NOT_FOUND_BY_ID')) {
    define('PERMISSION_NOT_FOUND_BY_ID', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_NOT_FOUND_BY_ID');
}
if (!defined('ROLE_NOT_FOUND_BY_NAME')) {
    define('ROLE_NOT_FOUND_BY_NAME', APP_NOTICE_DOMAIN . 'ERROR.ROLE_NOT_FOUND_BY_NAME');
}
if (!defined('ROLE_NOT_FOUND_BY_ID')) {
    define('ROLE_NOT_FOUND_BY_ID', APP_NOTICE_DOMAIN . 'ERROR.ROLE_NOT_FOUND_BY_ID');
}
if (!defined('PERMISSION_ALREADY_EXISTS')) {
    define('PERMISSION_ALREADY_EXISTS', APP_NOTICE_DOMAIN . 'ERROR.PERMISSION_ALREADY_EXISTS');
}
if (!defined('ROLE_ALREADY_EXISTS')) {
    define('ROLE_ALREADY_EXISTS', APP_NOTICE_DOMAIN . 'ERROR.ROLE_ALREADY_EXISTS');
}
if (!defined('GUARD_DOES_NOT_MATCH')) {
    define('GUARD_DOES_NOT_MATCH', APP_NOTICE_DOMAIN . 'ERROR.GUARD_DOES_NOT_MATCH');
}
if (!defined('WILDCARD_PERMISSION_INVALID_ARGUMENT')) {
    define('WILDCARD_PERMISSION_INVALID_ARGUMENT', APP_NOTICE_DOMAIN . 'ERROR.WILDCARD_PERMISSION_INVALID_ARGUMENT');
}
if (!defined('WILDCARD_PERMISSION_NOT_IMPLEMENTS_CONTRACT')) {
    define('WILDCARD_PERMISSION_NOT_IMPLEMENTS_CONTRACT', APP_NOTICE_DOMAIN . 'ERROR.WILDCARD_PERMISSION_NOT_IMPLEMENTS_CONTRACT');
}
if (!defined('WILDCARD_PERMISSION_NOT_PROPERLY_FORMATTED')) {
    define('WILDCARD_PERMISSION_NOT_PROPERLY_FORMATTED', APP_NOTICE_DOMAIN . 'ERROR.WILDCARD_PERMISSION_NOT_PROPERLY_FORMATTED');
}
if (!defined('COUPON_ADDED_TO_CART_SUCCESSFULLY')) {
    define('COUPON_ADDED_TO_CART_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.COUPON_ADDED_TO_CART_SUCCESSFULLY');
}
if (!defined('COULD_NOT_ADD_COUPON_TO_CART')) {
    define('COULD_NOT_ADD_COUPON_TO_CART', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_ADD_COUPON_TO_CART');
}
if (!defined('COULD_NOT_ADD_COUPON_TO_CART_NOT_VALID')) {
    define('COULD_NOT_ADD_COUPON_TO_CART_NOT_VALID', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_ADD_COUPON_TO_CART_NOT_VALID');
}
if (!defined('COULD_NOT_ADD_COUPON_TO_EMPTY_CART')) {
    define('COULD_NOT_ADD_COUPON_TO_EMPTY_CART', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_ADD_COUPON_TO_EMPTY_CART');
}
if (!defined('COULD_NOT_ADD_COUPON_TO_CART_YOU_HAVE_ALREADY_APPLIED_A_COUPON')) {
    define('COULD_NOT_ADD_COUPON_TO_CART_YOU_HAVE_ALREADY_APPLIED_A_COUPON', APP_NOTICE_DOMAIN . 'ERROR.COULD_NOT_ADD_COUPON_TO_CART_YOU_HAVE_ALREADY_APPLIED_A_COUPON');
}
if (!defined('DELETE_CART_ITEM_FAILED')) {
    define('DELETE_CART_ITEM_FAILED', APP_NOTICE_DOMAIN . 'ERROR.DELETE_CART_ITEM_FAILED');
}
if (!defined('BANNER_STATUS_CHANGED')) {
    define('BANNER_STATUS_CHANGED', APP_NOTICE_DOMAIN . 'MESSAGE.BANNER_STATUS_CHANGED');
}
if (!defined('BANNERS_REORDERED_SUCCESSFULLY')) {
    define('BANNERS_REORDERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BANNERS_REORDERED_SUCCESSFULLY');
}
if (!defined('SLIDER_STATUS_CHANGED')) {
    define('SLIDER_STATUS_CHANGED', APP_NOTICE_DOMAIN . 'MESSAGE.SLIDER_STATUS_CHANGED');
}
if (!defined('SLIDERS_REORDERED_SUCCESSFULLY')) {
    define('SLIDERS_REORDERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SLIDERS_REORDERED_SUCCESSFULLY');
}
if (!defined('USER_REGISTERED_SUCCESSFULLY')) {
    define('USER_REGISTERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_REGISTERED_SUCCESSFULLY');
}
if (!defined('USER_PROFILE_RETRIEVED_SUCCESSFULLY')) {
    define('USER_PROFILE_RETRIEVED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_PROFILE_RETRIEVED_SUCCESSFULLY');
}
if (!defined('USER_ADDED_SUCCESSFULLY')) {
    define('USER_ADDED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_ADDED_SUCCESSFULLY');
}
if (!defined('USER_ADMIN_CANNOT_BE_DELETED')) {
    define('USER_ADMIN_CANNOT_BE_DELETED', APP_NOTICE_DOMAIN . 'ERROR.USER_ADMIN_CANNOT_BE_DELETED');
}
if (!defined('USER_DELETED_SUCCESSFULLY')) {
    define('USER_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_DELETED_SUCCESSFULLY');
}
if (!defined('USER_RESTORED_SUCCESSFULLY')) {
    define('USER_RESTORED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_RESTORED_SUCCESSFULLY');
}
if (!defined('USER_CANNOT_BE_RESTORED')) {
    define('USER_CANNOT_BE_RESTORED', APP_NOTICE_DOMAIN . 'ERROR.USER_CANNOT_BE_RESTORED');
}
if (!defined('USER_TRASHED_LIST_RETRIEVED_SUCCESSFULLY')) {
    define('USER_TRASHED_LIST_RETRIEVED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_TRASHED_LIST_RETRIEVED_SUCCESSFULLY');
}
if (!defined('ADMINS_LISTED_SUCCESSFULLY')) {
    define('ADMINS_LISTED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ADMINS_LISTED_SUCCESSFULLY');
}
if (!defined('VENDORS_LISTED_SUCCESSFULLY')) {
    define('VENDORS_LISTED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.VENDORS_LISTED_SUCCESSFULLY');
}
if (!defined('CUSTOMERS_LISTED_SUCCESSFULLY')) {
    define('CUSTOMERS_LISTED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CUSTOMERS_LISTED_SUCCESSFULLY');
}
if (!defined('USERS_LISTED_SUCCESSFULLY')) {
    define('USERS_LISTED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USERS_LISTED_SUCCESSFULLY');
}
if (!defined('STAFFS_LISTED_SUCCESSFULLY')) {
    define('STAFFS_LISTED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.STAFFS_LISTED_SUCCESSFULLY');
}
if (!defined('USER_FETCHED_SUCCESSFULLY')) {
    define('USER_FETCHED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_FETCHED_SUCCESSFULLY');
}
if (!defined('USER_CANNOT_BE_UPDATED')) {
    define('USER_CANNOT_BE_UPDATED', APP_NOTICE_DOMAIN . 'ERROR.USER_CANNOT_BE_UPDATED');
}
if (!defined('USER_UPDATED_SUCCESSFULLY')) {
    define('USER_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_UPDATED_SUCCESSFULLY');
}
if (!defined('USER_LOGGED_IN_SUCCESSFULLY')) {
    define('USER_LOGGED_IN_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.USER_LOGGED_IN_SUCCESSFULLY');
}
if (!defined('EMAIL_VERIFICATION_LINK_SENT')) {
    define('EMAIL_VERIFICATION_LINK_SENT', APP_NOTICE_DOMAIN . 'MESSAGE.EMAIL_VERIFICATION_LINK_SENT');
}
if (!defined('INVALID_OTP')) {
    define('INVALID_OTP', APP_NOTICE_DOMAIN . 'ERROR.INVALID_OTP');
}
if (!defined('SHOP_CREATE_SUCCESSFULLY')) {
    define('SHOP_CREATE_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SHOP_CREATE_SUCCESSFULLY');
}
if (!defined('REVIEW_CREATED_SUCCESSFULLY')) {
    define('REVIEW_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.REVIEW_CREATED_SUCCESSFULLY');
}
if (!defined('REVIEW_UPDATED_SUCCESSFULLY')) {
    define('REVIEW_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.REVIEW_UPDATED_SUCCESSFULLY');
}
if (!defined('REVIEW_DELETED_SUCCESSFULLY')) {
    define('REVIEW_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.REVIEW_DELETED_SUCCESSFULLY');
}
if (!defined('INVALID_COUPON_CODE_OR_COUPON_CANNOT_BE_APPLIED_OR_COUPON_USAGE_LIMIT_REACHED')) {
    define('INVALID_COUPON_CODE_OR_COUPON_CANNOT_BE_APPLIED_OR_COUPON_USAGE_LIMIT_REACHED', APP_NOTICE_DOMAIN . 'ERROR.INVALID_COUPON_CODE_OR_COUPON_CANNOT_BE_APPLIED_OR_COUPON_USAGE_LIMIT_REACHED');
}
if (!defined('COUPON_APPLIED_SUCCESSFULLY')) {
    define('COUPON_APPLIED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.COUPON_APPLIED_SUCCESSFULLY');
}
if (!defined('COUPON_ALREADY_APPLIED')) {
    define('COUPON_ALREADY_APPLIED', APP_NOTICE_DOMAIN . 'MESSAGE.COUPON_ALREADY_APPLIED');
}
if (!defined('COUPON_DELETE_CART_WARNING')) {
    define('COUPON_DELETE_CART_WARNING', APP_NOTICE_DOMAIN . 'MESSAGE.COUPON_DELETE_CART_WARNING');
}
if (!defined('FILED_TO_CREATE_ORDER_TRY_AGAIN')) {
    define('FILED_TO_CREATE_ORDER_TRY_AGAIN', APP_NOTICE_DOMAIN . 'ERROR.FILED_TO_CREATE_ORDER_TRY_AGAIN');
}
if (!defined('CONTACT_CREATED_SUCCESSFULLY')) {
    define('CONTACT_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CONTACT_CREATED_SUCCESSFULLY');
}
if (!defined('REPLAY_SENT_SUCCESSFULLY')) {
    define('REPLAY_SENT_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.REPLAY_SENT_SUCCESSFULLY');
}
if (!defined('CONTACT_DELETED_SUCCESSFULLY')) {
    define('CONTACT_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CONTACT_DELETED_SUCCESSFULLY');
}
if (!defined('ALL_CONTACTS_DELETED_SUCCESSFULLY')) {
    define('ALL_CONTACTS_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ALL_CONTACTS_DELETED_SUCCESSFULLY');
}
if (!defined('ALL_READ_CONTACTS_DELETED_SUCCESSFULLY')) {
    define('ALL_READ_CONTACTS_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ALL_READ_CONTACTS_DELETED_SUCCESSFULLY');
}
if (!defined('COUNTRY_CREATED_SUCCESSFULLY')) {
    define('COUNTRY_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.COUNTRY_CREATED_SUCCESSFULLY');
}
if (!defined('COUNTRY_UPDATED_SUCCESSFULLY')) {
    define('COUNTRY_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.COUNTRY_UPDATED_SUCCESSFULLY');
}
if (!defined('COUNTRY_DELETED_SUCCESSFULLY')) {
    define('COUNTRY_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.COUNTRY_DELETED_SUCCESSFULLY');
}
if (!defined('COUNTRY_NOT_FOUND')) {
    define('COUNTRY_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.COUNTRY_NOT_FOUND');
}
if (!defined('GOVERNORATES_FETCHED_SUCCESSFULLY')) {
    define('GOVERNORATES_FETCHED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.GOVERNORATES_FETCHED_SUCCESSFULLY');
}
if (!defined('BULK_STATUS_UPDATED_SUCCESSFULLY')) {
    define('BULK_STATUS_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BULK_STATUS_UPDATED_SUCCESSFULLY');
}
if (!defined('GOVERNORATE_CREATED_SUCCESSFULLY')) {
    define('GOVERNORATE_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.GOVERNORATE_CREATED_SUCCESSFULLY');
}
if (!defined('GOVERNORATE_UPDATED_SUCCESSFULLY')) {
    define('GOVERNORATE_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.GOVERNORATE_UPDATED_SUCCESSFULLY');
}
if (!defined('GOVERNORATE_DELETED_SUCCESSFULLY')) {
    define('GOVERNORATE_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.GOVERNORATE_DELETED_SUCCESSFULLY');
}
if (!defined('PICKUP_LOCATION_CREATED_SUCCESSFULLY')) {
    define('PICKUP_LOCATION_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.PICKUP_LOCATION_CREATED_SUCCESSFULLY');
}
if (!defined('PICKUP_LOCATION_UPDATED_SUCCESSFULLY')) {
    define('PICKUP_LOCATION_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.PICKUP_LOCATION_UPDATED_SUCCESSFULLY');
}
if (!defined('PICKUP_LOCATION_DELETED_SUCCESSFULLY')) {
    define('PICKUP_LOCATION_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.PICKUP_LOCATION_DELETED_SUCCESSFULLY');
}
if (!defined('CITY_CREATED_SUCCESSFULLY')) {
    define('CITY_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CITY_CREATED_SUCCESSFULLY');
}
if (!defined('CITY_UPDATED_SUCCESSFULLY')) {
    define('CITY_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CITY_UPDATED_SUCCESSFULLY');
}
if (!defined('CITY_DELETED_SUCCESSFULLY')) {
    define('CITY_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CITY_DELETED_SUCCESSFULLY');
}
if (!defined('CREATE_DATA_SUCCESSFULLY')) {
    define('CREATE_DATA_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.CREATE_DATA_SUCCESSFULLY');
}
if (!defined('UPDATE_DATA_SUCCESSFULLY')) {
    define('UPDATE_DATA_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.UPDATE_DATA_SUCCESSFULLY');
}
if (!defined('DELETE_DATA_SUCCESSFULLY')) {
    define('DELETE_DATA_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.DELETE_DATA_SUCCESSFULLY');
}
if (!defined('INVALID_CREDENTIALS')) {
    define('INVALID_CREDENTIALS', APP_NOTICE_DOMAIN . 'ERROR.INVALID_CREDENTIALS');
}
if (!defined('INVALID_PRODUCT_TYPE')) {
    define('INVALID_PRODUCT_TYPE', APP_NOTICE_DOMAIN . 'ERROR.INVALID_PRODUCT_TYPE');
}
if (!defined('USER_NOT_VERIFIED')) {
    define('USER_NOT_VERIFIED', APP_NOTICE_DOMAIN . 'ERROR.USER_NOT_VERIFIED');
}
if (!defined('ACCOUNT_CREATED_BUT_OTP_FAILED')) {
    define('ACCOUNT_CREATED_BUT_OTP_FAILED', APP_NOTICE_DOMAIN . 'ERROR.ACCOUNT_CREATED_BUT_OTP_FAILED');
}
if (!defined('PLEASE_VERIFY_YOUR_EMAIL')) {
    define('PLEASE_VERIFY_YOUR_EMAIL', APP_NOTICE_DOMAIN . 'ERROR.PLEASE_VERIFY_YOUR_EMAIL');
}
if (!defined('SECTION_CREATED_SUCCESSFULLY')) {
    define('SECTION_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SECTION_CREATED_SUCCESSFULLY');
}
if (!defined('SECTION_UPDATED_SUCCESSFULLY')) {
    define('SECTION_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SECTION_UPDATED_SUCCESSFULLY');
}
if (!defined('SECTION_DELETED_SUCCESSFULLY')) {
    define('SECTION_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SECTION_DELETED_SUCCESSFULLY');
}
if (!defined('SECTIONS_REORDERED_SUCCESSFULLY')) {
    define('SECTIONS_REORDERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SECTIONS_REORDERED_SUCCESSFULLY');
}
if (!defined('TYPE_CREATED_SUCCESSFULLY')) {
    define('TYPE_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.TYPE_CREATED_SUCCESSFULLY');
}
if (!defined('TYPE_UPDATED_SUCCESSFULLY')) {
    define('TYPE_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.TYPE_UPDATED_SUCCESSFULLY');
}
if (!defined('TYPE_DELETED_SUCCESSFULLY')) {
    define('TYPE_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.TYPE_DELETED_SUCCESSFULLY');
}
if (!defined('SETTINGS_UPDATED_SUCCESSFULLY')) {
    define('SETTINGS_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SETTINGS_UPDATED_SUCCESSFULLY');
}
if (!defined('ROLE_FETCHED_SUCCESSFULLY')) {
    define('ROLE_FETCHED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLE_FETCHED_SUCCESSFULLY');
}
if (!defined('ROLES_FETCHED_SUCCESSFULLY')) {
    define('ROLES_FETCHED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLES_FETCHED_SUCCESSFULLY');
}
if (!defined('ROLE_ADDED_SUCCESSFULLY')) {
    define('ROLE_ADDED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLE_ADDED_SUCCESSFULLY');
}
if (!defined('ROLE_UPDATED_SUCCESSFULLY')) {
    define('ROLE_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLE_UPDATED_SUCCESSFULLY');
}
if (!defined('ROLE_DELETED_SUCCESSFULLY')) {
    define('ROLE_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLE_DELETED_SUCCESSFULLY');
}
if (!defined('CANNOT_DELETE_ROLE_WITH_ASSIGNED_USERS')) {
    define('CANNOT_DELETE_ROLE_WITH_ASSIGNED_USERS', APP_NOTICE_DOMAIN . 'ERROR.CANNOT_DELETE_ROLE_WITH_ASSIGNED_USERS');
}
if (!defined('ROLE_ASSIGNED_SUCCESSFULLY')) {
    define('ROLE_ASSIGNED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLE_ASSIGNED_SUCCESSFULLY');
}
if (!defined('ROLE_REMOVED_SUCCESSFULLY')) {
    define('ROLE_REMOVED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.ROLE_REMOVED_SUCCESSFULLY');
}
if (!defined('PERMISSIONS_FETCHED_SUCCESSFULLY')) {
    define('PERMISSIONS_FETCHED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.PERMISSIONS_FETCHED_SUCCESSFULLY');
}
if (!defined('PERMISSION_ASSIGNED_SUCCESSFULLY')) {
    define('PERMISSION_ASSIGNED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.PERMISSION_ASSIGNED_SUCCESSFULLY');
}
if (!defined('BRAND_CREATED_SUCCESSFULLY')) {
    define('BRAND_CREATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BRAND_CREATED_SUCCESSFULLY');
}
if (!defined('BRAND_UPDATED_SUCCESSFULLY')) {
    define('BRAND_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BRAND_UPDATED_SUCCESSFULLY');
}
if (!defined('BRAND_DELETED_SUCCESSFULLY')) {
    define('BRAND_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BRAND_DELETED_SUCCESSFULLY');
}
if (!defined('SHOP_RETRIEVED_SUCCESSFULLY')) {
    define('SHOP_RETRIEVED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SHOP_RETRIEVED_SUCCESSFULLY');
}
if (!defined('SHOP_UPDATED_SUCCESSFULLY')) {
    define('SHOP_UPDATED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SHOP_UPDATED_SUCCESSFULLY');
}
if (!defined('SHOP_DELETED_SUCCESSFULLY')) {
    define('SHOP_DELETED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.SHOP_DELETED_SUCCESSFULLY');
}
if (!defined('CANNOT_DELETE_CATEGORY_WITH_ASSOCIATED_RESOURCES')) {
    define('CANNOT_DELETE_CATEGORY_WITH_ASSOCIATED_RESOURCES', APP_NOTICE_DOMAIN . 'ERROR.CANNOT_DELETE_CATEGORY_WITH_ASSOCIATED_RESOURCES');
}
if (!defined('POINTS_ADDED_SUCCESSFULLY')) {
    define('POINTS_ADDED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.POINTS_ADDED_SUCCESSFULLY');
}
if (!defined('CART_NOT_FOUND')) {
    define('CART_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.CART_NOT_FOUND');
}
if (!defined('ERROR_CREATING_INVOICE')) {
    define('ERROR_CREATING_INVOICE', APP_NOTICE_DOMAIN . 'ERROR.ERROR_CREATING_INVOICE');
}
if (!defined('ERROR_ADDING_ITEMS_TO_ORDER')) {
    define('ERROR_ADDING_ITEMS_TO_ORDER', APP_NOTICE_DOMAIN . 'ERROR.ERROR_ADDING_ITEMS_TO_ORDER');
}
if (!defined('ERROR_CREATING_TRANSACTION')) {
    define('ERROR_CREATING_TRANSACTION', APP_NOTICE_DOMAIN . 'ERROR.ERROR_CREATING_TRANSACTION');
}
if (!defined('CHECKOUT_SUCCESSFUL')) {
    define('CHECKOUT_SUCCESSFUL', APP_NOTICE_DOMAIN . 'MESSAGE.CHECKOUT_SUCCESSFUL');
}
if (!defined('MISSING_PAYMENT_ID')) {
    define('MISSING_PAYMENT_ID', APP_NOTICE_DOMAIN . 'ERROR.MISSING_PAYMENT_ID');
}
if (!defined('INVALID_PAYMENT_RESPONSE')) {
    define('INVALID_PAYMENT_RESPONSE', APP_NOTICE_DOMAIN . 'ERROR.INVALID_PAYMENT_RESPONSE');
}
if (!defined('PAYMENT_SUCCESSFUL')) {
    define('PAYMENT_SUCCESSFUL', APP_NOTICE_DOMAIN . 'MESSAGE.PAYMENT_SUCCESSFUL');
}
if (!defined('BRANDS_REORDERED_SUCCESSFULLY')) {
    define('BRANDS_REORDERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.BRANDS_REORDERED_SUCCESSFULLY');
}
if (!defined('FLASH_SALE_REORDERED_SUCCESSFULLY')) {
    define('FLASH_SALE_REORDERED_SUCCESSFULLY', APP_NOTICE_DOMAIN . 'MESSAGE.FLASH_SALE_REORDERED_SUCCESSFULLY');
}
if (!defined('FAST_SHIPPING_NOT_AVAILABLE')) {
    define('FAST_SHIPPING_NOT_AVAILABLE', APP_NOTICE_DOMAIN . 'MESSAGE.FAST_SHIPPING_NOT_AVAILABLE');
}
if (!defined('FAST_SHIPPING_OUTSIDE_HOURS')) {
    define('FAST_SHIPPING_OUTSIDE_HOURS', APP_NOTICE_DOMAIN . 'MESSAGE.FAST_SHIPPING_OUTSIDE_HOURS');
}
if (!defined('FAST_SHIPPING_GOVERNORATE_DISABLED')) {
    define('FAST_SHIPPING_GOVERNORATE_DISABLED', APP_NOTICE_DOMAIN . 'MESSAGE.FAST_SHIPPING_GOVERNORATE_DISABLED');
}
if (!defined('FAST_SHIPPING_PRODUCT_NOT_ELIGIBLE')) {
    define('FAST_SHIPPING_PRODUCT_NOT_ELIGIBLE', APP_NOTICE_DOMAIN . 'MESSAGE.FAST_SHIPPING_PRODUCT_NOT_ELIGIBLE');
}
if (!defined('FAST_SHIPPING_MIXED_CART')) {
    define('FAST_SHIPPING_MIXED_CART', APP_NOTICE_DOMAIN . 'MESSAGE.FAST_SHIPPING_MIXED_CART');
}
if (!defined('VARIANT_STOCK_EXCEEDED')) {
    define('VARIANT_STOCK_EXCEEDED', APP_NOTICE_DOMAIN . 'ERROR.VARIANT_STOCK_EXCEEDED');
}
if (!defined('PRODUCT_STOCK_EXCEEDED')) {
    define('PRODUCT_STOCK_EXCEEDED', APP_NOTICE_DOMAIN . 'ERROR.PRODUCT_STOCK_EXCEEDED');
}
if (!defined('CANNOT_ASSIGN_ROLE_TO_USER')) {
    define('CANNOT_ASSIGN_ROLE_TO_USER', APP_NOTICE_DOMAIN . 'ERROR.CANNOT_ASSIGN_ROLE_TO_USER');
}
if (!defined('COD_NOT_AVAILABLE_FOR_PICKUP')) {
    define('COD_NOT_AVAILABLE_FOR_PICKUP', APP_NOTICE_DOMAIN . 'ERROR.COD_NOT_AVAILABLE_FOR_PICKUP');
}
if (!defined('INVALID_PAYMENT_METHOD')) {
    define('INVALID_PAYMENT_METHOD', APP_NOTICE_DOMAIN . 'ERROR.INVALID_PAYMENT_METHOD');
}
if (!defined('TRANSACTION_NOT_FOUND')) {
    define('TRANSACTION_NOT_FOUND', APP_NOTICE_DOMAIN . 'ERROR.TRANSACTION_NOT_FOUND');
}
if (!defined('UNAUTHORIZED_TRANSACTION_ACCESS')) {
    define('UNAUTHORIZED_TRANSACTION_ACCESS', APP_NOTICE_DOMAIN . 'ERROR.UNAUTHORIZED_TRANSACTION_ACCESS');
}
if (!defined('PAYMENT_GATEWAY_UNAVAILABLE')) {
    define('PAYMENT_GATEWAY_UNAVAILABLE', APP_NOTICE_DOMAIN . 'ERROR.PAYMENT_GATEWAY_UNAVAILABLE');
}
if (!defined('NOTIFICATIONS_FETCHED')) {
    define('NOTIFICATIONS_FETCHED', APP_NOTICE_DOMAIN . 'MESSAGE.NOTIFICATIONS_FETCHED');
}
if (!defined('UNREAD_NOTIFICATIONS_FETCHED')) {
    define('UNREAD_NOTIFICATIONS_FETCHED', APP_NOTICE_DOMAIN . 'MESSAGE.UNREAD_NOTIFICATIONS_FETCHED');
}
if (!defined('NOTIFICATION_MARKED_READ')) {
    define('NOTIFICATION_MARKED_READ', APP_NOTICE_DOMAIN . 'MESSAGE.NOTIFICATION_MARKED_READ');
}
if (!defined('ALL_NOTIFICATIONS_MARKED_READ')) {
    define('ALL_NOTIFICATIONS_MARKED_READ', APP_NOTICE_DOMAIN . 'MESSAGE.ALL_NOTIFICATIONS_MARKED_READ');
}
if (!defined('NOTIFICATION_DELETED')) {
    define('NOTIFICATION_DELETED', APP_NOTICE_DOMAIN . 'MESSAGE.NOTIFICATION_DELETED');
}
if (!defined('ALL_NOTIFICATIONS_DELETED')) {
    define('ALL_NOTIFICATIONS_DELETED', APP_NOTICE_DOMAIN . 'MESSAGE.ALL_NOTIFICATIONS_DELETED');
}
if (!defined('QUANTITY_MINIMUM')) {
    define('QUANTITY_MINIMUM', APP_NOTICE_DOMAIN . 'cart.inventory.quantity_minimum');
}
if (!defined('GIFT_VARIANT_NOT_AVAILABLE')) {
    define('GIFT_VARIANT_NOT_AVAILABLE', APP_NOTICE_DOMAIN . 'cart.inventory.gift_variant_not_available');
}
if (!defined('GIFT_VARIANT_NO_STOCK')) {
    define('GIFT_VARIANT_NO_STOCK', APP_NOTICE_DOMAIN . 'cart.inventory.gift_variant_no_stock');
}
if (!defined('QUANTITY_EXCEEDS_STOCK')) {
    define('QUANTITY_EXCEEDS_STOCK', APP_NOTICE_DOMAIN . 'cart.inventory.quantity_exceeds_stock');
}
if (!defined('RESERVED_STOCK_INSUFFICIENT')) {
    define('RESERVED_STOCK_INSUFFICIENT', APP_NOTICE_DOMAIN . 'cart.inventory.reserved_stock_insufficient');
}
if (!defined('PHYSICAL_STOCK_INSUFFICIENT')) {
    define('PHYSICAL_STOCK_INSUFFICIENT', APP_NOTICE_DOMAIN . 'cart.inventory.physical_stock_insufficient');
}
