<?php

namespace Tests\Feature\Coupon;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Marvel\Database\Models\Coupon;
use Marvel\Database\Models\CouponTargeting;
use Tests\TestCase;

/**
 * FOR UPDATE Lock Behavior Test
 *
 * This test verifies that SELECT ... FOR UPDATE actually acquires
 * an exclusive row lock that blocks concurrent access.
 *
 * LIMITATION: This test uses single-connection simulation.
 * True multi-connection blocking requires:
 * - Two separate database connections
 * - One connection holding a transaction open
 * - Second connection attempting to acquire the same lock
 * - Measuring actual wait/block behavior
 *
 * Real concurrent verification requires either:
 * 1. Multi-process test harness (PHP forking)
 * 2. External test script with two mysql clients
 * 3. Actual TiDB staging environment
 */
class ForUpdateLockTest extends TestCase
{
    use RefreshDatabase;

    private function createCoupon(array $overrides = []): Coupon
    {
        $code = 'TEST-' . Str::random(8);
        return Coupon::create(array_merge([
            'code' => $code,
            'slug' => Str::slug($code),
            'name' => 'Test Coupon',
            'discount_type' => 'percentage',
            'discount' => 10,
            'start_date' => now()->subDay(),
            'end_date' => now()->addMonth(),
            'status' => true,
        ], $overrides));
    }

    /**
     * Test that FOR UPDATE lock is generated by Eloquent.
     *
     * This verifies the SQL is correct, but does NOT prove blocking.
     */
    public function test_for_update_generates_correct_sql(): void
    {
        $coupon = $this->createCoupon();
        CouponTargeting::create([
            'coupon_id' => $coupon->id,
            'require_claim' => true,
            'max_claims' => 10,
        ]);

        // Enable query logging
        DB::enableQueryLog();

        // Execute the same query from CouponClaimService
        CouponTargeting::query()
            ->where('coupon_id', $coupon->id)
            ->lockForUpdate()
            ->first();

        $queries = DB::getQueryLog();
        DB::disableQueryLog();

        // Verify FOR UPDATE is in the SQL
        $this->assertCount(1, $queries);
        $sql = $queries[0]['query'];

        // SQLite doesn't support FOR UPDATE, but MySQL/TiDB do
        // In SQLite tests, the query will be without FOR UPDATE
        // This is a known limitation - real FOR UPDATE behavior requires MySQL/TiDB
        if (DB::getDriverName() === 'mysql') {
            $this->assertStringContainsString('for update', strtolower($sql));
        } else {
            // SQLite - just verify the query executed
            $this->assertTrue(true, 'SQLite does not support FOR UPDATE - skipping SQL verification');
        }
    }

    /**
     * Test lock acquisition within transaction.
     *
     * Verifies the lock is acquired inside a transaction context.
     */
    public function test_lock_acquired_in_transaction(): void
    {
        $coupon = $this->createCoupon();
        $targeting = CouponTargeting::create([
            'coupon_id' => $coupon->id,
            'require_claim' => true,
            'max_claims' => 10,
        ]);

        $result = DB::transaction(function () use ($coupon) {
            $locked = CouponTargeting::query()
                ->where('coupon_id', $coupon->id)
                ->lockForUpdate()
                ->first();

            return $locked;
        });

        $this->assertNotNull($result);
        $this->assertEquals($targeting->id, $result->id);
    }

    /**
     * Test that transaction rollback releases locks.
     *
     * Simulates rollback scenario - lock should be released.
     */
    public function test_rollback_releases_lock(): void
    {
        $coupon = $this->createCoupon();
        CouponTargeting::create([
            'coupon_id' => $coupon->id,
            'require_claim' => true,
            'max_claims' => 10,
        ]);

        try {
            DB::transaction(function () use ($coupon) {
                // Acquire lock
                CouponTargeting::query()
                    ->where('coupon_id', $coupon->id)
                    ->lockForUpdate()
                    ->first();

                // Force rollback
                throw new \Exception('Force rollback');
            });
        } catch (\Exception $e) {
            // Expected
        }

        // After rollback, we should be able to acquire lock again
        $result = DB::transaction(function () use ($coupon) {
            return CouponTargeting::query()
                ->where('coupon_id', $coupon->id)
                ->lockForUpdate()
                ->first();
        });

        $this->assertNotNull($result);
    }

    /**
     * Test nested transaction behavior.
     *
     * Laravel uses savepoints for nested transactions.
     */
    public function test_nested_transaction_lock(): void
    {
        $coupon = $this->createCoupon();
        $targeting = CouponTargeting::create([
            'coupon_id' => $coupon->id,
            'require_claim' => true,
            'max_claims' => 10,
        ]);

        DB::transaction(function () use ($coupon, $targeting) {
            $outer = CouponTargeting::query()
                ->where('coupon_id', $coupon->id)
                ->lockForUpdate()
                ->first();

            $this->assertNotNull($outer);

            DB::transaction(function () use ($coupon, $targeting) {
                $inner = CouponTargeting::query()
                    ->where('coupon_id', $coupon->id)
                    ->lockForUpdate()
                    ->first();

                $this->assertNotNull($inner);
            });
        });

        $this->assertTrue(true); // If we reach here, nested transactions work
    }

    /**
     * Document multi-connection test requirements.
     *
     * This is NOT a real test - it documents what SHOULD be tested
     * in a true concurrency environment.
     */
    public function test_multi_connection_blocking_requirements(): void
    {
        $this->markTestSkipped(
            'Multi-connection FOR UPDATE blocking test requires:' . PHP_EOL .
            '1. Two separate PDO connections to the same database' . PHP_EOL .
            '2. Connection A: BEGIN; SELECT ... FOR UPDATE; (hold open)' . PHP_EOL .
            '3. Connection B: BEGIN; SELECT ... FOR UPDATE; (should WAIT)' . PHP_EOL .
            '4. Measure Connection B wait time > 0' . PHP_EOL .
            '5. Connection A: COMMIT;' . PHP_EOL .
            '6. Connection B: should then acquire lock' . PHP_EOL .
            PHP_EOL .
            'This cannot be tested in PHPUnit without:' . PHP_EOL .
            '- Process forking (pcntl extension)' . PHP_EOL .
            '- External test harness' . PHP_EOL .
            '- Actual TiDB staging with manual verification'
        );
    }

    /**
     * Verify lock target is deterministic.
     *
     * All claims for the same coupon lock the same parent row.
     */
    public function test_lock_target_is_deterministic(): void
    {
        $coupon = $this->createCoupon();
        $targeting = CouponTargeting::create([
            'coupon_id' => $coupon->id,
            'require_claim' => true,
            'max_claims' => 10,
        ]);

        // Execute the lock query multiple times
        $results = [];
        for ($i = 0; $i < 5; $i++) {
            DB::enableQueryLog();

            $result = CouponTargeting::query()
                ->where('coupon_id', $coupon->id)
                ->lockForUpdate()
                ->first();

            $queries = DB::getQueryLog();
            DB::disableQueryLog();

            $results[] = [
                'sql' => $queries[0]['query'],
                'bindings' => $queries[0]['bindings'],
                'id' => $result->id,
            ];
        }

        // All queries should target the same row
        $firstId = $results[0]['id'];
        foreach ($results as $result) {
            $this->assertEquals($firstId, $result['id']);
        }

        // All queries should be identical
        $firstSql = $results[0]['sql'];
        foreach ($results as $result) {
            $this->assertEquals($firstSql, $result['sql']);
        }
    }
}
