<?php

declare(strict_types=1);

namespace Tests\Feature\Notifications;

use App\Notifications\UserOrderCreatedNotification;
use Illuminate\Broadcasting\BroadcastEvent;
use Illuminate\Notifications\Events\BroadcastNotificationCreated;
use Illuminate\Support\Facades\Queue;

/**
 * Proves that the Pusher broadcast job generated by the 'broadcast'
 * notification channel is explicitly queued on meem-medium — NOT the default
 * queue — while the database channel keeps persisting as before.
 *
 * This distinguishes the Notification/Listener queue from the
 * Broadcast/Pusher queue: the broadcast channel's BroadcastNotificationCreated
 * event must resolve to a queued BroadcastEvent on meem-medium.
 */
class BroadcastQueueAssignmentTest extends NotificationE2ETestCase
{
    public function test_broadcast_job_is_queued_on_meem_medium(): void
    {
        Queue::fake();

        $user = $this->createUser('user');
        $order = $this->createOrder($user);

        // sendNow executes the channels synchronously; the broadcast channel
        // must push its BroadcastEvent onto meem-medium.
        $user->notifyNow(new UserOrderCreatedNotification($order));

        Queue::assertPushedOn('meem-medium', BroadcastEvent::class, function (BroadcastEvent $job) {
            return $job->event instanceof BroadcastNotificationCreated;
        });
    }

    public function test_broadcast_job_never_uses_default_queue(): void
    {
        Queue::fake();

        $user = $this->createUser('user');
        $order = $this->createOrder($user);

        $user->notifyNow(new UserOrderCreatedNotification($order));

        $pushedJobs = Queue::pushedJobs();
        $this->assertArrayHasKey(BroadcastEvent::class, $pushedJobs, 'No BroadcastEvent was queued.');

        foreach ($pushedJobs[BroadcastEvent::class] as $pushed) {
            $this->assertSame('meem-medium', $pushed['queue'], 'BroadcastEvent must not land on the default queue.');
        }
    }

    public function test_database_notification_still_persists(): void
    {
        Queue::fake();

        $user = $this->createUser('user');
        $order = $this->createOrder($user);

        $user->notifyNow(new UserOrderCreatedNotification($order));

        $this->assertDatabaseNotification($user, 'order.created');
    }

    public function test_notification_sending_job_uses_meem_medium(): void
    {
        Queue::fake();

        $user = $this->createUser('user');
        $order = $this->createOrder($user);

        // Queued path: the notification job itself must use meem-medium.
        $user->notify(new UserOrderCreatedNotification($order));

        Queue::assertPushedOn('meem-medium', \Illuminate\Notifications\SendQueuedNotifications::class);
    }
}